# Exercise


In [8]:
import numpy as np
import pandas as pd



 ### 1.  How likely is it that you roll doubles when rolling two dice?

In [14]:
n_dice = 2
n_column = 2

In [34]:
n_trials = 10000
n_rows = 10000

In [35]:
rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(n_rows, n_column)

In [36]:
rolls

array([[6, 4],
       [2, 4],
       [6, 2],
       ...,
       [5, 2],
       [4, 1],
       [1, 5]])

In [37]:
df = pd.DataFrame(rolls)

In [38]:
successes = df[0] == df[1]

In [39]:
successes.mean()

0.1658

###  2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [40]:
n_coins = 8

In [41]:
n_column = 8

In [46]:
flips = np.random.choice(["H", "T"], n_trials * n_coins).reshape(n_rows, n_column)

In [47]:
df = pd.DataFrame(flips)

In [50]:
succeses = df == 'H'

In [58]:
(succeses.sum(axis=1) == 3).mean()

0.2209

In [59]:
(succeses.sum(axis=1) > 3).mean()

0.637

### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?



In [62]:

n_column = 2

In [73]:
((np.random.random([n_rows, n_column]) <= 0.25).sum(axis=1) == 2).mean()

0.059

### 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [95]:
(np.random.normal(3, 1.5, size = [10000, 5]).sum(axis=1) <= 17).mean()

0.7286

5. Compare Heights

- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
- Since you have means and standard deviations, you can use np.random.normal to generate observations.
- If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?



In [99]:
bro_bro = np.random.normal(178, 8, size=[10000, 1])
bro_bro

array([[188.30370534],
       [193.82475421],
       [190.94341179],
       ...,
       [192.17072648],
       [177.79245747],
       [162.98374903]])

In [101]:
gamer_grils = np.random.normal(170, 6, size=[10000, 1])
gamer_grils

array([[167.43145917],
       [163.44143529],
       [161.98690285],
       ...,
       [175.74701184],
       [169.94424127],
       [159.66148164]])

In [105]:
(bro_bro < gamer_grils).mean()

0.2096

### 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

What is the probability that we observe an installation issue within the first 150 students that download anaconda?



In [127]:
df = pd.DataFrame(np.random.random([10000, 50]) > (1/250))
(df.sum(axis=1) == 50).mean()

0.8186

In [129]:
a = pd.DataFrame(np.random.random([10000, 100]) > (1/250))
(a.sum(axis=1) == 100).mean()

0.6631

In [133]:
(pd.DataFrame(np.random.random([10000, 150]) > (1/250)).sum(axis=1) != 150).mean()

0.4526

### 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

#### How likely is it that a food truck will show up sometime this week?



In [141]:
((np.random.random([10000, 3]) < 0.7).sum(axis=1) == 0).mean()

0.025

#### 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [186]:
df = pd.DataFrame(np.random.randint(1, 366, size=[10000, 23]))

In [191]:
(df.nunique(axis=1) != 23).mean()

0.5009

In [192]:
df = pd.DataFrame(np.random.randint(1, 366, size=[10000, 20]))

In [193]:
(df.nunique(axis=1) != 20).mean()

0.408

In [194]:
df = pd.DataFrame(np.random.randint(1, 366, size=[10000, 40]))

In [195]:
(df.nunique(axis=1) != 40).mean()

0.8941